### PR TITLE
Add support for building using meson

### PR DESCRIPTION
**Pull request by cpba**
Only tested on fedora 27, please share your results.

Easiest way to try it:

```
meson build && cd build
ninja
```

### CODE REVIEW

**Comment by PSI-Rockin** [comment]
On OS X, I get a bunch of compiler errors when building using your instructions. They seem to be related to a lack of C++11 support:

```
../src/firmware.hpp:25:9: error: unknown type name 'constexpr'
        constexpr static int SIZE = 1024 * 256; //262 KB
```

Is there a way to force the compiler to use C++11 using meson?

**Comment by nadiaholmquist** [comment]
To fix this, wet the C++ version in `project()` as described here:

http://mesonbuild.com/howtox.html#set-default-cc-language-version

**Comment by cpba** [comment]
@PSI-Rockin Sure, that's my fault. It was building fine for me so I didn't realise it'd be necessary.

I've updated it as @Nadia-h suggests, please test it again when you have time. I'm sure it's not the only thing I missed.

**Comment by PSI-Rockin** [comment]
@cpba I've tested and it works now, but it runs very slowly on Mario Kart DS. Looks like the optimization flags are missing. I use -O2 in the qmake file.

EDIT: Adding "--buildtype=release" fixes the optimization problems. I'll commit and merge the changes.

**Pull request merged**
